// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"SamuraiLab3/server/data"
)

// Injectors from modules.go:

func ComposeApiServer(port int) (*ForumApiServer, error) {
	db, err := data.ProvideDbConnection()
	if err != nil {
		return nil, err
	}
	repository := data.ProvideRepository(db)
	handlerFunc := data.ProvideHttpHandler(repository)
	forumApiServer := &ForumApiServer{
		Port:        port,
		HandlerFunc: handlerFunc,
	}
	return forumApiServer, nil
}
